version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_DATABASE: survey-api
    volumes:
      - ./.docker/:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/survey-api
    restart: always
    command: bash -c "npm install --only=prod && npm install ts-node-dev -D --no-save && npm run debug"
    environment:
      - MONGO_URL=${MONGO_URL}
    volumes:
      - ./dist/:/usr/src/survey-api/dist
      - ./package.json:/usr/src/survey-api/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
