name: CI

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install node_modules
        run: |
          npm set-script prepare ""
          npm ci
      - name: ESLint
        run: npx eslint 'src/**'
      - name: Create coverage
        run: npm run coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}